### ISSUE TITLE
Recipient request

### ISSUE THREAD

**Issue by dejimania** [BuildForSDGCohort2/Team-025-Frontend#9]
#### Feature Description
At the landing page there will be a button for the user to make use of the app as a recipient of blood and blood product

#### User story
As a user I want to request for blood so I can get a donor(s)/pint(s) of blood as prescribed by the doctor.
- [ ] A recipient button to click on and navigate to a request page.
- [ ] A request form to fill in the blood group,rhesus factor ,blood product(either drop down or radio button) and the quantity required.
- [ ] A submit / request button
- [ ] A post API to save the information to Database
- [ ] A display / message if there is an immediate match or not and another message sent to the matched donor notifying her/him
- [ ] A logic that calculate the closest donor or blood bank to the recipient.

#### Additional consideration
Geo-location API

###### Question
Any addition of what we might want to support

**Comment by Busry** [comment]
let the team know what you are working on via this comment section.

**Comment by niel98** [comment]
Working on the recipient request. Noted.

**Comment by dejimania** [comment]
Working on the post API to save request information to Database.
